### PR TITLE
Restart Camera1 Frame Processing After Taking a Picture - Fixes Issue 824

### LINKED ISSUE #824: After taking a picture, frame process will not receive any frame in Camera1.
Hi,
In Full1PictureRecorder.java, it stops the preview callback by set to null before takePicture.
The preview callback will be set back on onPictureTaken function but forget to re-add callback buffer.

Reference:
https://developer.android.com/reference/android/hardware/Camera
Camera.PreviewCallback: a callback object that receives a copy of the preview frame, or null to stop receiving callbacks and "clear the buffer queue".

### PR DESCRIPTION
**Pull request by jeffreyfjohnson**
- Fixes #824 
- Tests: No tests existed for the only edited class, `Full1PictureRecorder`
- Docs updated: No, fixes behind the scenes bug

### Solution
Took solution from @natario1 's comment on issue, simply needed to re-setup the frame manager after capturing a photo

### CODE REVIEW

File: cameraview/src/main/java/com/otaliastudios/cameraview/picture/Full1PictureRecorder.java [hunk 1]
```diff
@@ -67,7 +70,21 @@ public void onPictureTaken(byte[] data, final Camera camera) {
...
+                        }
+                        // Need to re-setup the frame manager, otherwise no frames are processed
+                        // after takePicture() is called
+                        mEngine.getFrameManager().setUp(
+                                mEngine.getFrameProcessingFormat(),
+                                previewStreamSize,
+                                mEngine.getAngles()
+                        );
+
                         camera.startPreview(); // This is needed, read somewhere in the docs.
```
Comment (natario1) [inline cameraview/src/main/java/com/otaliastudios/cameraview/picture/Full1PictureRecorder.java:88]: Could you put all these lines (74-88) into a condition `if (mEngine.getState().isAtLeast(CameraState.PREVIEW))` ? This way we're sure that the preview is still running and previewStreamSize is really not null as you said.

**Comment by jeffreyfjohnson** [comment]
@natario1 changes addressed. Happy to help, very impressed with the library you've put together here!
